### ISSUE TITLE
Issue with example notebook shown in binder

### ISSUE THREAD

**Issue by CasperWA** [materialscloud-org/materialscloud-voila-template#1]
When pressing the button to choose `Li` and `H`, the elements turn blue in the periodic table. A color which is otherwise not reachable through normal toggling.
Maybe you are missing to update some traitlets or other? I am not completely sure.
The issue only occurs for the binder in this repository, for the similar binder in the `aiidalab-voila` template, this didn't seem to be an issue. However, the state was random (or at least different) in that one (maybe also here).

**Comment by giovannipizzi** [comment]
I mentioned this issue in osscar-org/widget-periodictable#4 - let's continue the discussion there as it's a problem of the widget and not of the template of voila
